services:
  conservices-screen:
    platform: linux/amd64
    image: hub.demolite.de/demoreg/conservices-screen
    container_name: conservices-screen
    restart: always
    build:
      context: .
      dockerfile: Conservices.Screen/Dockerfile
    ports:
      - "8090:8080"